"""Validated theorem-maturity audit data and its Markdown projection.

Promoted from ``scripts/theorem_maturity_audit.py`` (SC-18) so the
release-bundle receipt validator can import the projection instead of
executing the script's module namespace via ``runpy`` — module-level side
effects inside a receipt validator are unacceptable, and the name-string
coupling was invisible to refactoring tools. The wrapper script remains the
maintenance entry point and re-exports these names.
"""

from __future__ import annotations

from dataclasses import asdict
from pathlib import Path
from typing import Any

__all__ = ["render_markdown", "validate_audit"]


def validate_audit(root: Path | None = None) -> dict[str, Any]:
    """Return package-validated rows; the default root is this repository."""
    resolved = root if root is not None else Path(__file__).resolve().parents[3]
    return _validate_audit(resolved)


def _validate_audit(root: Path) -> dict[str, Any]:
    """Return package-validated rows in the Markdown renderer's input shape."""
    from fep_lean.catalogue.semantics import load_theorem_maturity
    from fep_lean.catalogue.topics import FEPTopicCatalogue

    audit = load_theorem_maturity(root / "config" / "theorem_maturity.yaml")
    catalogue = FEPTopicCatalogue.from_yaml(root / "config" / "topics.yaml")
    if [record.id for record in audit.records] != [
        topic.id for topic in catalogue.topics
    ]:
        raise ValueError("audit topic IDs do not match config/topics.yaml")
    rows = []
    for record in audit.records:
        row = asdict(record)
        row["disposition"] = record.disposition.value
        rows.append(row)
    return {
        "schema_version": audit.schema_version,
        "review_date": audit.review_date,
        "native_evidence": audit.native_evidence,
        "status_policy": audit.status_policy,
        "topics": rows,
    }


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def render_markdown(data: dict[str, Any]) -> str:
    """Render the checked-in Markdown projection from validated audit data."""
    lines = [
        "# Theorem maturity audit",
        "",
        "<!-- AUTO-GENERATED by scripts/theorem_maturity_audit.py; edit config/theorem_maturity.yaml. -->",
        "",
        "This audit reviews the semantic reach of each catalogue row beyond",
        "sorry-free compilation. It is deliberately separate from",
        "`mathlib_status`: `real` records that the declared Lean/Mathlib sketch",
        "is a native compilation target, not that the FEP-facing prose has been",
        "fully formalized.",
        "",
        f"**Review date:** `{data['review_date']}`<br>",
        f"**Native evidence boundary:** {data['native_evidence']}",
        "",
        "A `scope_gap` or `assumption_gap` is an honest follow-up boundary, not a",
        "compiler failure. Dispositions are maintained mathematical judgments,",
        "not values inferred from successful compilation.",
        "",
        "## Status-change policy",
        "",
        data["status_policy"],
        "A status change must update the catalogue source, regenerate YAML and the",
        "aggregate, rerun the native Lean probe, and retain the receipt in",
        "`CHANGELOG.md`.",
        "",
        "## Dispositions",
        "",
        "- `formalized`: the primary theorem directly states the maintained narrowed invariant.",
        "- `proxy`: useful foundational formal fact, with a narrower scope than the prose.",
        "- `conditional_proxy`: meaningful conditional fact whose hypotheses are explicit.",
        "- `structural_proxy`: type, set, metric, or algebra closure fact used as an anchor.",
        "- `scope_gap`: the theorem compiles but omits a named FEP or physical invariant.",
        "- `assumption_gap`: the stated assumptions are vacuous or encode the conclusion.",
        "",
        "## Topic review",
        "",
        "| ID | Primary theorem | Intended invariant | Assumption review | Non-vacuity review | Acceptance probe | Disposition |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in data["topics"]:
        lines.append(
            "| "
            + " | ".join(
                _cell(row[field])
                for field in (
                    "id",
                    "primary_theorem",
                    "invariant",
                    "assumption_review",
                    "non_vacuity",
                    "acceptance_probe",
                    "disposition",
                )
            )
            + " |"
        )
    lines.extend(
        [
            "",
            "## Source links",
            "",
            "- [Maintained audit data](../config/theorem_maturity.yaml)",
            "- [Catalogue metadata](../config/topics.yaml)",
            "- [Lean body registry](../src/fep_lean/catalogue/registry.py)",
            "- [Family-owned Lean bodies](../src/fep_lean/catalogue/bodies/)",
            "- [Native verification command](cli-reference.md)",
            "",
        ]
    )
    return "\n".join(lines)
