"""Fail-closed, source-preserving manuscript variable rendering."""

from __future__ import annotations

import os
import re
import shutil
import tempfile
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from fep_lean.output.fsutil import atomic_write_bytes, atomic_write_text
from fep_lean.output.publication_metadata import (
    PublicationMetadataError,
    load_graphical_abstract,
)

PLACEHOLDER_RE = re.compile(r"\{\{([^}]+)\}\}")
# Every shell block this repository publishes is a promise a reader can run.
# ``scripts/render_manuscript.py --check`` validates
# ``manuscript/manuscript_vars.yaml`` and the generated appendix, both build
# products excluded by ``.gitignore``. On a checkout that has not built them
# it exits 1 with "test collection cache is missing", so a block that runs the
# check without a generator ahead of it publishes a recipe that fails on the
# first try. Four blocks did, the paper's own Reproducibility Statement
# among them.
_SHELL_FENCE_LANGUAGES: tuple[str, ...] = ("bash", "console", "shell", "sh")
_SHELL_FENCE_RE = re.compile(
    r"^(?P<indent>[ \t]*)```(?:"
    + "|".join(_SHELL_FENCE_LANGUAGES)
    + r")[^\n]*\n(?P<body>.*?)^(?P=indent)```",
    re.DOTALL | re.MULTILINE,
)
_RENDER_CHECK_TOKEN = "scripts/render_manuscript.py --check"
# What actually regenerates the projections the check validates. The
# generating form of ``render_manuscript.py`` does not: it rebuilds the test
# cache but never writes ``manuscript_vars.yaml``, so with that file absent it
# exits 1 with "stale manuscript projections" exactly as ``--check`` does.
_PROJECTION_GENERATORS: tuple[str, ...] = ("fep-lean catalogue",)
# The check counts the collected test suite, so it imports pytest and
# pytest-timeout -- both `dev` extras. A block that opens with a bare
# `uv sync --locked` *removes* them from an existing environment, and the
# check then exits 1 with "required pytest collection distribution is
# missing: pytest". The conclusion's Reproducibility Statement opened exactly
# that way.
_SYNC_TOKEN = "uv sync"
_SYNC_TEST_EXTRA = "--extra dev"
# Files whose shell blocks are published as reproduction instructions. Blocks
# under a generated or vendored tree are not this repository's promise.
_PUBLISHED_COMMAND_GLOBS: tuple[str, ...] = (
    "*.md",
    ".github/workflows/*.yml",
    "docs/*.md",
    "manuscript/*.md",
    "scripts/*.md",
    "src/fep_lean/*.md",
    "tests/*.md",
)
SOURCE_EXCLUDES = frozenset(
    {
        "AGENTS.md",
        "README.md",
        "preamble.md",
        "09z_unified_formalism_catalogue.md",
    }
)
# Generated appendices that carry no ``{{placeholder}}`` and therefore need no
# substitution, but must still reach the rendered tree. They were previously
# only excluded, so an injected-tree render dropped the entire 155-topic
# formalism catalogue -- roughly two thirds of the paper -- with no diagnostic.
VERBATIM_SOURCES: tuple[str, ...] = ("09z_unified_formalism_catalogue.md",)
MANUSCRIPT_ASSETS: dict[str, tuple[Path, Path]] = {
    "../docs/formalism-atlas.svg": (
        Path("docs/formalism-atlas.svg"),
        Path("assets/formalism-atlas.svg"),
    ),
    "../docs/formalism-atlas.html": (
        Path("docs/formalism-atlas.html"),
        Path("assets/formalism-atlas.html"),
    ),
    "../docs/formal-kernel-dashboard.svg": (
        Path("docs/formal-kernel-dashboard.svg"),
        Path("assets/formal-kernel-dashboard.svg"),
    ),
    "../docs/formal-kernel-dashboard.html": (
        Path("docs/formal-kernel-dashboard.html"),
        Path("assets/formal-kernel-dashboard.html"),
    ),
    # Generated by ``fep-lean catalogue`` (write_all_catalogue_figures). Without
    # this entry the resolved tree keeps a ``../`` path that escapes it.
    "../output/figures/status_distribution.png": (
        Path("output/figures/status_distribution.png"),
        Path("assets/status_distribution.png"),
    ),
    # 04e's area-distribution paragraph described a figure the document did not
    # contain; the figure now ships, so its asset must resolve too.
    "../output/figures/topics_by_area.png": (
        Path("output/figures/topics_by_area.png"),
        Path("assets/topics_by_area.png"),
    ),
    # Rasterized from the SVG projections by
    # ``scripts/build_manuscript_figures.py`` (fep_lean.output.svg_raster).
    # 04f and 04g cite these two as PNGs; without the rows here the combined
    # render kept an escaping ``../`` path and aborted on
    # ``! Unable to load picture or PDF file``.
    "../output/figures/formalism-atlas.png": (
        Path("output/figures/formalism-atlas.png"),
        Path("assets/formalism-atlas.png"),
    ),
    "../output/figures/formal-kernel-dashboard.png": (
        Path("output/figures/formal-kernel-dashboard.png"),
        Path("assets/formal-kernel-dashboard.png"),
    ),
}


class ManuscriptRenderError(ValueError):
    """Raised before output is written when manuscript variables are unresolved."""


def flatten_variables(data: Any, prefix: str = "") -> dict[str, str]:
    """Flatten nested manuscript data to deterministic dotted keys."""
    flat: dict[str, str] = {}
    if not isinstance(data, Mapping):
        return flat
    for raw_key, value in data.items():
        key = f"{prefix}.{raw_key}" if prefix else str(raw_key)
        if isinstance(value, Mapping):
            flat.update(flatten_variables(value, key))
        elif isinstance(value, list):
            flat[key] = ", ".join(str(item) for item in value)
        elif isinstance(value, bool):
            flat[key] = str(value).lower()
        elif value is None:
            flat[key] = ""
        else:
            flat[key] = str(value)
    return flat


def manuscript_source_files(source_dir: Path) -> tuple[Path, ...]:
    """Return authored Markdown inputs in stable order."""
    source = Path(source_dir)
    return tuple(
        path for path in sorted(source.glob("*.md")) if path.name not in SOURCE_EXCLUDES
    )


def published_command_files(project_root: Path) -> tuple[Path, ...]:
    """Return the files whose shell blocks are published as instructions."""
    root = Path(project_root)
    found: set[Path] = set()
    for pattern in _PUBLISHED_COMMAND_GLOBS:
        found.update(path for path in root.glob(pattern) if path.is_file())
    return tuple(sorted(found))


def unreproducible_command_blocks(project_root: Path) -> tuple[str, ...]:
    """Return published shell blocks whose render check cannot pass as written.

    ``render_manuscript.py --check`` validates generated projections it does
    not create. A block that runs it without first running a generator --
    ``fep-lean catalogue``, or the generating form of the script itself --
    exits 1 on any checkout that has not already built them, which is every
    fresh clone. This audit reads each block in order and reports the ones
    that ask a reader to run a check nothing in the block can satisfy.
    """

    root = Path(project_root)
    failures: list[str] = []
    for path in published_command_files(root):
        text = path.read_text(encoding="utf-8")
        for fence in _SHELL_FENCE_RE.finditer(text):
            body = fence.group("body")
            index = body.find(_RENDER_CHECK_TOKEN)
            if index < 0:
                continue
            preceding = body[:index]
            offset = fence.start("body") + index
            line_number = text.count("\n", 0, offset) + 1
            try:
                display = path.relative_to(root).as_posix()
            except ValueError:  # pragma: no cover - defensive
                display = path.name
            if not any(token.strip() in preceding for token in _PROJECTION_GENERATORS):
                failures.append(
                    f"{display}:{line_number}: "
                    f"`{_RENDER_CHECK_TOKEN}` runs with no generator ahead of "
                    "it; add `uv run fep-lean catalogue` earlier in the same "
                    "block"
                )
            starved = [
                line
                for line in preceding.splitlines()
                if _SYNC_TOKEN in line and _SYNC_TEST_EXTRA not in line
            ]
            if starved:
                failures.append(
                    f"{display}:{line_number}: "
                    f"`{_RENDER_CHECK_TOKEN}` follows `{starved[0].strip()}`, "
                    f"which leaves no pytest to collect; pass "
                    f"`{_SYNC_TEST_EXTRA}`"
                )
    return tuple(failures)


def unresolved_placeholders(
    source_dir: Path, variables: Mapping[str, Any]
) -> tuple[str, ...]:
    """Return unknown variables and malformed placeholder delimiters."""
    flat = flatten_variables(variables)
    unresolved: list[str] = []
    for path in manuscript_source_files(source_dir):
        content = path.read_text(encoding="utf-8")
        matches = tuple(PLACEHOLDER_RE.finditer(content))
        for match in matches:
            key = match.group(1).strip()
            # A literal ellipsis is used once while explaining expression
            # syntax; it is not a publication variable.
            if key == "…":
                continue
            if key not in flat:
                line_number = content.count("\n", 0, match.start()) + 1
                display_key = " ".join(key.split())
                unresolved.append(f"{path.name}:{line_number}: {display_key}")
        unmatched = list(content)
        for match in matches:
            unmatched[match.start() : match.end()] = " " * (match.end() - match.start())
        unmatched_text = "".join(unmatched)
        # Double closing braces occur naturally in LaTeX. A remaining opening
        # pair, however, can only be a malformed publication placeholder because
        # every balanced placeholder span was masked above.
        for match in re.finditer(re.escape("{{"), unmatched_text):
            line_number = content.count("\n", 0, match.start()) + 1
            unresolved.append(f"{path.name}:{line_number}: unclosed opening delimiter")
    return tuple(unresolved)


def substitute_placeholders(
    content: str, variables: Mapping[str, Any], *, strict: bool = True
) -> str:
    """Return ``content`` with every ``{{placeholder}}`` resolved.

    The renderer calls this after :func:`unresolved_placeholders` has already
    refused any unknown key, and keeps ``strict`` so an unknown one raises
    rather than printing a literal ``{{token}}`` onto a page.

    A caller comparing rendered output against its source (see
    ``fep_lean.output.render_log.stale_render_defects``) needs the same text
    the renderer produced but may hold an older variable projection, so it
    passes ``strict=False`` and leaves what it cannot resolve alone.
    """

    flat = flatten_variables(variables)

    def replace(match: re.Match[str]) -> str:
        key = match.group(1).strip()
        if key == "…":
            return match.group(0)
        if strict:
            return flat[key]
        return flat.get(key, match.group(0))

    return PLACEHOLDER_RE.sub(replace, content)


def _atomic_text(path: Path, text: str) -> None:
    """Deprecated alias; shared implementation lives in ``output.fsutil``."""
    atomic_write_text(path, text)


def _atomic_bytes(path: Path, data: bytes) -> None:
    """Deprecated alias; shared implementation lives in ``output.fsutil``."""
    atomic_write_bytes(path, data)


def _replace_render_tree(staged: Path, destination: Path) -> None:
    """Replace one renderer-owned destination tree, restoring it on failure."""
    backup: Path | None = None
    if destination.exists():
        raw_backup = tempfile.mkdtemp(
            prefix=f".{destination.name}.backup-", dir=destination.parent
        )
        backup = Path(raw_backup)
        backup.rmdir()
        os.replace(destination, backup)
    try:
        os.replace(staged, destination)
    except BaseException:
        if backup is not None and backup.exists() and not destination.exists():
            os.replace(backup, destination)
        raise
    if backup is not None and backup.exists():
        shutil.rmtree(backup)


def render_manuscript(
    source_dir: Path,
    destination_dir: Path,
    variables: Mapping[str, Any],
) -> tuple[Path, ...]:
    """Render authored Markdown into a separate build directory.

    The entire source set is validated and staged before the renderer-owned
    destination tree is replaced. An error cannot leave a partial update, and
    files removed from the source or its referenced-asset roster cannot remain
    in a later publication.
    """
    source = Path(source_dir).resolve()
    destination = Path(destination_dir).resolve()
    if source == destination or source.is_relative_to(destination):
        raise ManuscriptRenderError(
            "source must be outside the renderer-owned destination tree"
        )
    if destination.exists() and not destination.is_dir():
        raise ManuscriptRenderError("destination must be a directory")
    unresolved = unresolved_placeholders(source, variables)
    if unresolved:
        raise ManuscriptRenderError(
            "unresolved manuscript placeholders:\n" + "\n".join(unresolved)
        )
    source_contents = {
        source_path: source_path.read_text(encoding="utf-8")
        for source_path in manuscript_source_files(source)
    }
    rendered_contents: dict[Path, str] = {
        source_path: substitute_placeholders(content, variables)
        for source_path, content in source_contents.items()
    }

    referenced_assets = {
        reference: paths
        for reference, paths in MANUSCRIPT_ASSETS.items()
        if any(reference in content for content in rendered_contents.values())
    }
    missing_assets = [
        str(source.parent / source_relative)
        for source_relative, _destination_relative in referenced_assets.values()
        if not (source.parent / source_relative).is_file()
    ]
    if missing_assets:
        raise ManuscriptRenderError(
            "referenced manuscript assets are missing:\n" + "\n".join(missing_assets)
        )
    asset_contents = {
        destination_relative: (source.parent / source_relative).read_bytes()
        for source_relative, destination_relative in referenced_assets.values()
    }
    graphical_abstract_requested = any(
        "publication.graphical_abstract." in content
        for content in source_contents.values()
    )
    if graphical_abstract_requested:
        try:
            graphical_abstract = load_graphical_abstract(source.parent)
        except PublicationMetadataError as exc:
            raise ManuscriptRenderError(str(exc)) from exc
        expected_variables = graphical_abstract.manuscript_variables()
        actual_variables = variables.get("publication")
        if not isinstance(actual_variables, Mapping) or (
            actual_variables.get("graphical_abstract") != expected_variables
        ):
            raise ManuscriptRenderError(
                "graphical abstract variables do not match the canonical asset"
            )
        asset_contents[Path(graphical_abstract.render_path)] = graphical_abstract.data

    for source_path, rendered_content in rendered_contents.items():
        for reference, (
            _source_relative,
            destination_relative,
        ) in referenced_assets.items():
            rendered_content = rendered_content.replace(
                reference, destination_relative.as_posix()
            )
        rendered_contents[source_path] = rendered_content

    # Verbatim generated appendices: no substitution, but they must ship.
    for verbatim_name in VERBATIM_SOURCES:
        verbatim_path = source / verbatim_name
        if verbatim_path.is_file():
            rendered_contents[verbatim_path] = verbatim_path.read_text(encoding="utf-8")

    destination.parent.mkdir(parents=True, exist_ok=True)
    staged = Path(
        tempfile.mkdtemp(prefix=f".{destination.name}.stage-", dir=destination.parent)
    )
    try:
        for source_path, rendered_content in rendered_contents.items():
            _atomic_text(staged / source_path.name, rendered_content)
        for destination_relative, asset_data in asset_contents.items():
            _atomic_bytes(staged / destination_relative, asset_data)
        _replace_render_tree(staged, destination)
    finally:
        if staged.exists():
            shutil.rmtree(staged)
    return tuple(destination / source_path.name for source_path in rendered_contents)
